### ISSUE TITLE
(feat) Exclure les PR avec un label WIP de la règle des 7 jours

### ISSUE THREAD

**Issue by b-durand** [CodeCorico/palantir#7]
Nous avons l'habitude de pousser les gens à ouvrir une PR avec le label `WIP` pour que ça soit visible et que les gens puissent contribuer au fil de l'eau. La règle des 7 jours ne peut pas s'appliquer dans ce cas.

**Comment by XavierBoubert** [comment]
The days counter to display the colors status will be configurable in a new release.
