### ISSUE TITLE
(bug) PR groupées

### ISSUE THREAD

**Issue by b-durand** [CodeCorico/palantir#9]
Définir des règles plus logiques ? Nous avons 3 PR groupées : 2 jaunes, et 1 rouge.
Faut-il synchro les couleurs ? Est-ce logique d'en devoir une sur un groupe de 3 ?

Quel est l'ordre de tri ? La rouge n'est pas à droite mais à gauche or c'est la plus ancienne.

**Comment by XavierBoubert** [comment]
If you have ideas for new rules, you can share them with us (or make a PR 👅 ).
Colours are independent because they are related to PRs. Groups are only there to gather related PRs together.

I have fixed the PRs sorting in groups.
